### ISSUE TITLE
command 'git.viewHistory' not found

### ISSUE THREAD

**Issue by lcruz4** [DonJayamanne/gitHistoryVSCode#238]
No output for git history specifically in the vscode output window but under log extension it says
```
[2018-02-14 08:54:53.282] [exthost1] [info] ExtensionService#_doActivateExtension donjayamanne.githistory {"startup":false,"activationEvent":"onCommand:git.viewHistory"}
[2018-02-14 08:54:53.282] [exthost1] [info] ExtensionService#loadCommonJSModule C:\Users\luiscruz\.vscode\extensions\donjayamanne.githistory-0.4.0\out\src\extension
```
This is the console output. Looks like the reflect-metadata module is the problem. @DonJayamanne 
```
console.ts:123 [Extension Host] Activating extension `donjayamanne.githistory` failed:  Cannot find module 'reflect-metadata'
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionService.ts:787 Activating extension `donjayamanne.githistory` failed: Cannot find module 'reflect-metadata'.
R._logMessageInConsole @ extensionService.ts:787
R._logOrShowMessage @ extensionService.ts:801
e.$localShowMessage @ mainThreadExtensionService.ts:32
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:126 command 'git.viewHistory' not found: Error: command 'git.viewHistory' not found
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1312:74)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1311:922
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:140:868)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:144:153)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:145:970)
    at n.Class.derive._creator._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:145:411)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:140:868)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:144:153)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:145:970)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:145:411)
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ titleControl.ts:241
e.fire @ event.ts:142
(anonymous) @ actions.ts:221
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
e.resolveOk @ lazyPromise.ts:65
e._receiveReply @ rpcProtocol.ts:135
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:123 [Extension Host] Here is the error stack:  Error: Cannot find module 'reflect-metadata'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\luiscruz\.vscode\extensions\donjayamanne.githistory-0.4.0\out\src\extension.js:14:5)
	at Object.<anonymous> (C:\Users\luiscruz\.vscode\extensions\donjayamanne.githistory-0.4.0\out\src\extension.js:108:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
```

**Comment by lcruz4** [comment]
running a npm install in the project directory fixes this.

**Comment by lcruz4** [comment]
Hi @km5es the issue is not fixed, but if you go to the project directory for this extension and run npm install it installs the missing modules.

I did the following
cd ~/.vscode/extensions/donjayamanne.githistory-0.4.0/
npm install

**Comment by km5es** [comment]
Thanks. I'll give it a go.

**Comment by km5es** [comment]
UPDATE: It's working, thanks! @lcruz4

**Comment by master-7** [comment]
I've the same problem

`command 'git.viewHistory' not found`

**Comment by DonJayamanne** [comment]
Please try re-installing the extension. Most likely a corrupt install of the extension.
Please re-open if the problem persists even after re-installing the extension.
Oh yes, please go into `console window` (`Help->Toggle Developer Tools`) to check if there are any errors.

**Comment by diegoquintanav** [comment]
I'm getting the same error

In the console I get mainly two errors
```
Activating extension 'donjayamanne.githistory' failed: Cannot find module '/home/diego/.vscode/extensions/donjayamanne.githistory-0.4.1/out/src/extension'.
```
and

```
notificationsAlerts.ts:40 Error: command 'git.viewFileHistory' not found
    at t._tryExecuteCommand (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2915:36)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2914:846
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._creator._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._completed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at Object.g [as _notify] (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at e.resolveOk (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3060:806)
    at e._receiveReply (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3126:708)
    at e._receiveOneMessage (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3126:6)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3124:863
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3127:942
    at e.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:171:344)
    at c (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:302:1008)
    at Socket.<anonymous> (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:303:171)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```
it seems the error is that vscode is not finding the extension, thus the second error. Can you see into this please? 

```
$ code --version
1.25.0
0f080e5267e829de46638128001aeb7ca2d6d50e
x64
```

**Comment by neilyoung** [comment]
Same here

1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64

**Comment by jblachly** [comment]
Appeared for me after the July update -- previously was working great.

**Comment by slothquanta** [comment]
Have the same error on Ubuntu 18.04 and code 1.32.3. @lcruz4 's answer helps fix it. Go to `/home/ywang393/.vscode/extensions/donjayamanne.githistory-0.4.6` and `npm install`.

**Comment by qiqingfu** [comment]
@slothquanta 按照你的方法我尝试了一下, 发现仍然没有作用

**Comment by x1y9** [comment]
After starting vscode, just wait for a while before executing ctrl-h.

**Comment by sudarshansb143** [comment]
After doing ```npm install``` in the ```C:\Users\ue\.vscode\extensions\donjayamanne.githistory-0.6.19``` 
I am getting  

```
C:\Users\ue\.vscode\extensions\donjayamanne.githistory-0.6.19>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: githistory@0.6.19
npm ERR! Found: jest@25.5.4
npm ERR! node_modules/jest
npm ERR!   dev jest@"^25.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jest@">=26 <27" from ts-jest@26.5.6
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"^26.4.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ue\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ue\AppData\Local\npm-cache\_logs\2022-01-27T06_47_48_603Z-debug.log
```

**Comment by sudarshansb143** [comment]
after some trial and error I found a workaround 

```
1. Uninstall the extension 
2. remove the directory from C:\Users\ue\.vscode\extensions (for windows)
3. Close VS code and reopen the vs code 
4. Install extension again and we are good to go
```
