### ISSUE TITLE
command 'git.viewHistory' not found

### ISSUE THREAD

**Issue by yihengli** [DonJayamanne/gitHistoryVSCode#284]
## Description

When use this extension, notification `command git.viewHistory not found` pops up. While other git extensions work well in vscode. Checked #238 

## Enviroment
OS: WIndows10 RS4
VSCode: 1.24.1
Extension: 0.4.1

## Other information

1. Tested by disable all other extensions, reinstall and enable gitHistory only. Same result
2. Tested with similar setup in MacOS, everything works well. 
3. Tested by using the `npm install` trick under the extension folder. Not work with following message:
```
fixed 0 of 5 vulnerabilities in 14222 scanned packages
  5 vulnerabilities required manual review and could not be updated
```

## Error Msg in Console
```
extensionService.ts:870 Activating extension 'donjayamanne.githistory' failed: Cannot find module './adapter/parsers/serviceRegistry'.
w._logMessageInConsole @ extensionService.ts:870
w._logOrShowMessage @ extensionService.ts:884
e.$localShowMessage @ mainThreadExtensionService.ts:32
e._doInvokeHandler @ rpcProtocol.ts:265
e._invokeHandler @ rpcProtocol.ts:250
e._receiveRequest @ rpcProtocol.ts:196
e._receiveOneMessage @ rpcProtocol.ts:178
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```
```
Error: command 'git.viewHistory' not found
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2736:332)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2736:187
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:157:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:45)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:157:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:45)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._creator._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._creator._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:149:807)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:153:85)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:896)
    at n.Class.derive._oncancel._completed (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:337)
    at e.resolveOk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2872:954)
    at e._receiveReply (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2937:345)
    at e._receiveOneMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2936:661)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2935:518
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2938:575
    at e.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:169:992)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:301:187)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
e.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
(anonymous) @ titleControl.ts:234
e.fire @ event.ts:140
(anonymous) @ actions.ts:221
v @ winjs.base.js:1224
enter @ winjs.base.js:916
_run @ winjs.base.js:1083
_chainedError @ winjs.base.js:1046
n @ winjs.base.js:751
then @ winjs.base.js:1451
enter @ winjs.base.js:762
_run @ winjs.base.js:1083
_setCompleteValue @ winjs.base.js:1067
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
l @ winjs.base.js:1828
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ winjs.base.js:1853
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
l @ winjs.base.js:1828
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ winjs.base.js:1853
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
g @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
e.resolveOk @ lazyPromise.ts:65
e._receiveReply @ rpcProtocol.ts:226
e._receiveOneMessage @ rpcProtocol.ts:184
(anonymous) @ rpcProtocol.ts:111
(anonymous) @ rpcProtocol.ts:307
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
console.ts:136 [Extension Host] Here is the error stack:  Error: Cannot find module './adapter/parsers/serviceRegistry'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:300)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\l5453\.vscode\extensions\donjayamanne.githistory-0.4.1\out\src\extension.js:18:27)
	at Object.<anonymous> (C:\Users\l5453\.vscode\extensions\donjayamanne.githistory-0.4.1\out\src\extension.js:102:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:300)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:759:932
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:760:25)
	at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:758:910)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:756:770)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:444:188)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:443:757
	at Array.map (native)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:443:732)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:442:14)
	at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:757:139)
	at t.$activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:646)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by osya** [comment]
I have similar issue.

```

console.ts:136 [Extension Host] Activating extension `donjayamanne.githistory` failed:  Cannot find module 'C:\Users\info_000\.vscode\extensions\donjayamanne.githistory-0.4.1\out\src\extension'
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] Here is the error stack:  Error: Cannot find module 'C:\Users\info_000\.vscode\extensions\donjayamanne.githistory-0.4.1\out\src\extension'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.t._load (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:814:682)
	at Function.o._load (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (e:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (e:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
	at e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:790:186
	at t._doActivateExtension (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:790:298)
	at t._activateExtension (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:789:187)
	at Object.actualActivateExtension (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:787:48)
	at e._activateExtension (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:188)
	at e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:451:757
	at Array.map (native)
	at e._activateExtensions (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:451:732)
	at e.activateByEvent (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:450:14)
	at t.activateByEvent (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:787:412)
	at t.$activateByEvent (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:791:885)
	at e._doInvokeHandler (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:87)
	at e._invokeHandler (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:779)
	at e._receiveRequest (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:851)
	at e._receiveOneMessage (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:620)
	at e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
	at e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
	at e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
	at e.fire (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
	at u (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
	at Socket.<anonymous> (e:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
extensionService.ts:892 Activating extension 'donjayamanne.githistory' failed: Cannot find module 'C:\Users\info_000\.vscode\extensions\donjayamanne.githistory-0.4.1\out\src\extension'.
w._logMessageInConsole @ extensionService.ts:892
w._logOrShowMessage @ extensionService.ts:906
e.$localShowMessage @ mainThreadExtensionService.ts:32
e._doInvokeHandler @ rpcProtocol.ts:261
e._invokeHandler @ rpcProtocol.ts:246
e._receiveRequest @ rpcProtocol.ts:192
e._receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
c @ ipc.net.ts:81
(anonymous) @ ipc.net.ts:108
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
notificationsAlerts.ts:40 Error: command 'git.viewHistory' not found
    at t._tryExecuteCommand (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2915:36)
    at file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2914:846
    at Object.g [as _notify] (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at l (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:159:45)
    at Object.g [as _notify] (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._creator._run (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._creator._completed (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at Object.g [as _notify] (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:807)
    at Object.enter (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:154:85)
    at n.Class.derive._oncancel._run (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:896)
    at n.Class.derive._oncancel._completed (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:337)
    at e.resolveOk (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3060:806)
    at e._receiveReply (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3126:708)
    at e._receiveOneMessage (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3126:6)
    at file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3124:863
    at file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3127:942
    at e.fire (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:171:344)
    at c (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:302:1008)
    at Socket.<anonymous> (file:///E:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303:171)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by DonJayamanne** [comment]
Please try re-installing the extension.
Looks like the extension hasn't been installed correctly

**Comment by yihengli** [comment]
After updating the VScode to 1.25.1, the problem has been solved.

As @DonJayamanne pointed out, the problem might be the re-installation I tried before hasn't been executed properly. 

Sometimes the extension icon still exists at right upper corner after uninstalling the extension and reloading the Vscode window. I tried it several time until the extension icon completely disappear. Re-installation after that solved the issue.

**Comment by pbwei** [comment]
1.30.0 vscode has this problem

**Comment by mbristol78** [comment]
tried to re-install a few times, but it still doesnt work...

Version: 1.31.1
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-15-generic

**Comment by miku86** [comment]
@mbristol78 

I solved it by:
1. uninstalling it from VSCode
2. deleting the git-history folder in `.vscode/extensions/` with `rm -rf`
3. re-installing it in VSCode

**Comment by LazerFX** [comment]
I have this issue only in the second VSCode window I open.  In the primary window, the git history works as expected.  In the second, I get `command 'git.viewHistory' not found` in the error bell.

If someone can let me know how I get error outputs, I'll happily supply them.

**Comment by jiapengwen** [comment]
reinstall is ok, thx
