### ISSUE TITLE
Wrong avatar

### ISSUE THREAD

**Issue by schmamps** [DonJayamanne/gitHistoryVSCode#287]
I've uninstalled and reinstalled, but this extension always shows the avatar of a *different* Andrew Champion (my legal name)

**Comment by heqiao** [comment]
Same issue. Funny thing is, days ago, my coworkers and I were googling each others' names to see how much google revealed our info. A girl's picture showed up for my name(I'm a guy). Today, that exact picture is showing as my avatar in vs code. Now, my coworkers must think I'm creepy...

**Comment by johan0stman** [comment]
> Same issue. Funny thing is, days ago, my coworkers and I were googling each others' names to see how much google revealed our info. A girl's picture showed up for my name(I'm a guy). Today, that exact picture is showing as my avatar in vs code. Now, my coworkers must think I'm creepy...

have you tried clearing your cache ?

**Comment by heqiao** [comment]
> > Same issue. Funny thing is, days ago, my coworkers and I were googling each others' names to see how much google revealed our info. A girl's picture showed up for my name(I'm a guy). Today, that exact picture is showing as my avatar in vs code. Now, my coworkers must think I'm creepy...
> 
> have you tried clearing your cache ?

I'm no longer using that laptop, but I installed git history on my new machine, still showing that girl's picture

**Comment by johan0stman** [comment]
> > > Same issue. Funny thing is, days ago, my coworkers and I were googling each others' names to see how much google revealed our info. A girl's picture showed up for my name(I'm a guy). Today, that exact picture is showing as my avatar in vs code. Now, my coworkers must think I'm creepy...
> > 
> > 
> > have you tried clearing your cache ?
> 
> I'm no longer using that laptop, but I installed git history on my new machine, still showing that girl's picture

your lucky tho... i have an asian mob boss's picture

**Comment by baij930312** [comment]
me too , how to hide avatar? i want not to see it...

**Comment by baij930312** [comment]
me too , How to hide avatar?

**Comment by mjaseem** [comment]
I am having this issue in version  0.4.6. Is the fix not released yet?

**Comment by ole1986** [comment]
Unfortunately the changes apply to 0.4.7 which is not yet released...

**Comment by ole1986** [comment]
Please double check with the latest version (0.4.8) if this issue still exist

**Comment by sevdog** [comment]
> Please double check with the latest version (0.4.8) if this issue still exist

Today I have updated the extension, now I do not see any avatar at all.

**Comment by ole1986** [comment]
@sevdog can you try to disable the Avatar cache from its extension  configuration 

`gitHistory.avatarCacheExpiration = 0`

Please also note the github API is limited to a max number of requests (in free edition).
You can check the remaining requests with the below url and let us know

https://api.github.com/rate_limit

Thank you

**Comment by sevdog** [comment]
@ole1986 I have tried with avatar cache disabled (also after restarting vscode) but I do not see any difference.

I have also checked on extension's logs but there is no clue about it. Are these requests been logged?

**Comment by ole1986** [comment]
Unfortunately they not seem to be logged. 

May this be a possible proxy issue? Have you already tried to open the rate_limit url and can you also try the below link from the machine you are using git history extension

https://api.github.com/users/ole1986

And check if you receive a json result

**Comment by sevdog** [comment]
I do not see any problem with APIs:

![image](https://user-images.githubusercontent.com/13779643/69956155-8d6a6e80-14ff-11ea-906a-f44b9e8953e2.png)
![image](https://user-images.githubusercontent.com/13779643/69956242-bee33a00-14ff-11ea-8b24-8baaa0c55f27.png)

I have tried to check the extension in debug but I have got the following error:
```

Error: Failed to lookup view "~/develop/gitHistoryVSCode/out/browser/index.ejs" in views directory "/home/davide/views"
	at Function.render (~/develop/gitHistoryVSCode/node_modules/express/lib/application.js:580:17)
	at ServerResponse.render (~/develop/gitHistoryVSCode/node_modules/express/lib/response.js:1012:7)
	at ServerHost.rootRequestHandler (~/develop/gitHistoryVSCode/out/src/server/serverHost.js:90:13)
	at ~/develop/gitHistoryVSCode/out/src/server/serverHost.js:69:22
	at Layer.handle [as handle_request] (~/develop/gitHistoryVSCode/node_modules/express/lib/router/layer.js:95:5)
	at next (~/develop/gitHistoryVSCode/node_modules/express/lib/router/route.js:137:13)
	at Route.dispatch (~/develop/gitHistoryVSCode/node_modules/express/lib/router/route.js:112:3)
	at Layer.handle [as handle_request] (~/develop/gitHistoryVSCode/node_modules/express/lib/router/layer.js:95:5)
	at ~/develop/gitHistoryVSCode/node_modules/express/lib/router/index.js:281:22
	at Function.process_params (~/develop/gitHistoryVSCode/node_modules/express/lib/router/index.js:335:12)
	at next (~/develop/gitHistoryVSCode/node_modules/express/lib/router/index.js:275:10)
	at cors (~/develop/gitHistoryVSCode/node_modules/cors/lib/index.js:188:7)
	at ~/develop/gitHistoryVSCode/node_modules/cors/lib/index.js:224:17
	at originCallback (~/develop/gitHistoryVSCode/node_modules/cors/lib/index.js:214:15)
	at ~/develop/gitHistoryVSCode/node_modules/cors/lib/index.js:219:13
	at optionsCallback (~/develop/gitHistoryVSCode/node_modules/cors/lib/index.js:199:9)
	at corsMiddleware (~/develop/gitHistoryVSCode/node_modules/cors/lib/index.js:204:7)
	at Layer.handle [as handle_request] (~/develop/gitHistoryVSCode/node_modules/express/lib/router/layer.js:95:5)
	at trim_prefix (~/develop/gitHistoryVSCode/node_modules/express/lib/router/index.js:317:13)
	at ~/develop/gitHistoryVSCode/node_modules/express/lib/router/index.js:284:7
	at Function.process_params (~/develop/gitHistoryVSCode/node_modules/express/lib/router/index.js:335:12)
	at next (~/develop/gitHistoryVSCode/node_modules/express/lib/router/index.js:275:10)
	at SendStream.error (~/develop/gitHistoryVSCode/node_modules/serve-static/index.js:121:7)
	at SendStream.emit (events.js:200:13)
	at SendStream.error (~/develop/gitHistoryVSCode/node_modules/send/index.js:270:17)
	at SendStream.onStatError (~/develop/gitHistoryVSCode/node_modules/send/index.js:421:12)
	at next (~/develop/gitHistoryVSCode/node_modules/send/index.js:763:28)
	at ~/develop/gitHistoryVSCode/node_modules/send/index.js:771:23
	at FSReqCallback.oncomplete (fs.js:165:21)
```

**Comment by ole1986** [comment]
Have you started `npm run watchBuild` to build the browser src?

**Comment by sevdog** [comment]
I did not found `watchBuild` but `watchReact` and `buildReact`.

In debug mode I see that `getContributors` fails with a 404.
I have both tried with a private repo and with _this_ repo.

I have done a little check: it seems that API url is not builded correctly, and `repoPath` is not working as expected.
The right url should be:
```
https://api.github.com/repos/DonJayamanne/gitHistoryVSCode/contributors
```
While as of now the following url is requested:
```
https://api.github.com/repos/DonJayamanne/gitHistoryVSCode.git/contributors
```
The `.git` seems to break everything.

**Comment by ole1986** [comment]
Oh... I see. Great job!

So the workaround is to change to remote from

`https://github.com/<user>/<repoName>.git`
to 
`https://github.com/<user>/<repoName>`

using 

`git remote set-url origin <URL>`
