### ISSUE TITLE
ENOENT error when trying to view file content on line history

### ISSUE THREAD

**Issue by Adondriel** [DonJayamanne/gitHistoryVSCode#323]
Getting this error:
```
git log --pretty=oneline -n1 faccc5cbd36cc819b7714acc64cd16124d9d4d0d  (completed in 0.096s)
git show --pretty=oneline --decorate=full --numstat faccc5cbd36cc819b7714acc64cd16124d9d4d0d  (completed in 0.143s)
git show --numstat --pretty=oneline -M faccc5cbd36cc819b7714acc64cd16124d9d4d0d  (completed in 0.105s)
git show --name-status --pretty=oneline -M faccc5cbd36cc819b7714acc64cd16124d9d4d0d  (completed in 0.106s)
git remote get-url origin  (completed in 0.117s)
git rev-parse --show-toplevel  (completed in 0.001s)
{"stack":"Error: spawn C:/Program Files/Git/bin/git ENOENT\n    at _errnoException (util.js:1024:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n    at onErrorNT (internal/child_process.js:372:16)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","message":"spawn C:/Program Files/Git/bin/git ENOENT","code":"ENOENT","errno":"ENOENT","syscall":"spawn C:/Program Files/Git/bin/git","path":"C:/Program Files/Git/bin/git","spawnargs":["rev-parse","--show-toplevel"]}
git rev-parse --show-toplevel  (completed in 0.002s)
```
steps: viewing line history, click a commit, choose 'view file contents', it errors.

**Comment by ole1986** [comment]
PR #316 fixes this the way displaying the workspace file contents.
But IMO it should display the file content of the selected commit.

so, this needs more investigation until it is properly fixed

**Comment by ole1986** [comment]
Possible duplicate with #283

**Comment by ole1986** [comment]
@Adondriel can you please double check with the version 0.4.3 if it still exist?

Also, it more looks like git binary could not be found. Can you confirm the binary "git.exe" is installed on your machine (C:/Program Files/Git/bin/git.exe)?
