### ISSUE TITLE
`Compare` command produces error

### ISSUE THREAD

**Issue by osya** [DonJayamanne/gitHistoryVSCode#374]
`Compare` command produces the error
```
 ERR Cannot read property 'workspaceFolder' of undefined: TypeError: Cannot read property 'workspaceFolder' of undefined
	at GitFileHistoryCommandHandler.<anonymous> (C:\Users\info.DESKTOP-4KD5D80\.vscode\extensions\donjayamanne.githistory-0.4.6\out\src\commandHandlers\fileCommit\fileHistory.js:113:120)
	at Generator.next (<anonymous>)
	at __awaiter (C:\Users\info.DESKTOP-4KD5D80\.vscode\extensions\donjayamanne.githistory-0.4.6\out\src\commandHandlers\fileCommit\fileHistory.js:19:71)
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\info.DESKTOP-4KD5D80\.vscode\extensions\donjayamanne.githistory-0.4.6\out\src\commandHandlers\fileCommit\fileHistory.js:15:12)
	at GitFileHistoryCommandHandler.compareFileAcrossCommits (C:\Users\info.DESKTOP-4KD5D80\.vscode\extensions\donjayamanne.githistory-0.4.6\out\src\commandHandlers\fileCommit\fileHistory.js:112:16)
	at CommandHandlerManager.registerCommand.disposable.commandManager.registerCommand.args (C:\Users\info.DESKTOP-4KD5D80\.vscode\extensions\donjayamanne.githistory-0.4.6\out\src\commandHandlers\handlerManager.js:39:21)
	at d._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:477:621)
	at d.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:478:6)
	at d._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by DonJayamanne** [comment]
Closing this issue due to inactivity.
If this issue still exists, please do get back to us or please feel free to file a new issue
